Repository srinikandula/aultra-paints-backend, pull requests merged in 2025-02, with the labels that each got.

#74 Qa
  controllers/authController.js
  controllers/transactionController.js
  controllers/transactionLedgerController.js
  controllers/transferController.js
  controllers/userController.js
  models/TransactionLedger.js
  package.json
  redeem.html
  routes/transactionLedgerRoute.js
  routes/usersRoutes.js
  services/transactionService.js
  utils/logger.js
Labels: size:L

#76 Minor changes
  controllers/transactionLedgerController.js
Labels: size:XS

#77 pagination changes in rewardschemes
  controllers/rewardSchemes.controller.js
Labels: size:S

#78 added static otp for dealer mapping
  controllers/authController.js
  controllers/userController.js
  services/user.service.js
Labels: size:M

#80 Add couponSeries Range
  controllers/batchnumberController.js
  models/batchnumber.js
Labels: size:S

#81 updated the batchCreation
  controllers/batchnumberController.js
  models/Transaction.js
  services/transactionService.js
Labels: size:S
